basePath: /
host: localhost:5888
info:
  contact:
    email: support@example.com
    name: API Support
  description: API for managing community watch shifts, bookings, and reports
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Night Owls Control Shift Scheduler API
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
