services:
  night-owls:
    image: night-owls-go-local
    container_name: night-owls-app-local
    restart: unless-stopped
    environment:
      - SERVER_PORT=5888
      - "DATABASE_PATH=:memory:"
      - DEV_MODE=true
      - JWT_SECRET=test-secret-key-for-local-testing
      - VAPID_PUBLIC_KEY=
      - VAPID_PRIVATE_KEY=
      - VAPID_SUBJECT=
      - TWILIO_ACCOUNT_SID=
      - TWILIO_AUTH_TOKEN=
      - TWILIO_FROM_NUMBER=
    volumes:
      - night_owls_data_local:/app/data
    networks:
      - night_owls_network_local
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  caddy:
    image: caddy:2-alpine
    container_name: night-owls-caddy-local
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./Caddyfile.local:/etc/caddy/Caddyfile
      - ./app/build:/srv
      - caddy_data_local:/data
      - caddy_config_local:/config
    networks:
      - night_owls_network_local
    depends_on:
      night-owls:
        condition: service_healthy

volumes:
  night_owls_data_local:
    driver: local
  caddy_data_local:
    driver: local
  caddy_config_local:
    driver: local

networks:
  night_owls_network_local:
    driver: bridge 