// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Booking struct {
	BookingID   int64          `json:"booking_id"`
	UserID      int64          `json:"user_id"`
	ScheduleID  int64          `json:"schedule_id"`
	ShiftStart  time.Time      `json:"shift_start"`
	ShiftEnd    time.Time      `json:"shift_end"`
	BuddyUserID sql.NullInt64  `json:"buddy_user_id"`
	BuddyName   sql.NullString `json:"buddy_name"`
	Attended    bool           `json:"attended"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Outbox struct {
	OutboxID    int64          `json:"outbox_id"`
	MessageType string         `json:"message_type"`
	Recipient   string         `json:"recipient"`
	Payload     sql.NullString `json:"payload"`
	Status      string         `json:"status"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	SentAt      sql.NullTime   `json:"sent_at"`
	RetryCount  sql.NullInt64  `json:"retry_count"`
	UserID      sql.NullInt64  `json:"user_id"`
}

type PushSubscription struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
	Endpoint  string         `json:"endpoint"`
	P256dhKey string         `json:"p256dh_key"`
	AuthKey   string         `json:"auth_key"`
	UserAgent sql.NullString `json:"user_agent"`
	Platform  sql.NullString `json:"platform"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Report struct {
	ReportID  int64          `json:"report_id"`
	BookingID int64          `json:"booking_id"`
	Severity  int64          `json:"severity"`
	Message   sql.NullString `json:"message"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Schedule struct {
	ScheduleID      int64          `json:"schedule_id"`
	Name            string         `json:"name"`
	CronExpr        string         `json:"cron_expr"`
	StartDate       sql.NullTime   `json:"start_date"`
	EndDate         sql.NullTime   `json:"end_date"`
	DurationMinutes int64          `json:"duration_minutes"`
	Timezone        sql.NullString `json:"timezone"`
}

type User struct {
	UserID    int64          `json:"user_id"`
	Phone     string         `json:"phone"`
	Name      sql.NullString `json:"name"`
	CreatedAt sql.NullTime   `json:"created_at"`
	Role      string         `json:"role"`
}
