// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type AuditEvent struct {
	EventID      int64          `json:"event_id"`
	EventType    string         `json:"event_type"`
	ActorUserID  sql.NullInt64  `json:"actor_user_id"`
	TargetUserID sql.NullInt64  `json:"target_user_id"`
	EntityType   string         `json:"entity_type"`
	EntityID     sql.NullInt64  `json:"entity_id"`
	Action       string         `json:"action"`
	Details      sql.NullString `json:"details"`
	IpAddress    sql.NullString `json:"ip_address"`
	UserAgent    sql.NullString `json:"user_agent"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Booking struct {
	BookingID   int64          `json:"booking_id"`
	UserID      int64          `json:"user_id"`
	ScheduleID  int64          `json:"schedule_id"`
	ShiftStart  time.Time      `json:"shift_start"`
	ShiftEnd    time.Time      `json:"shift_end"`
	BuddyUserID sql.NullInt64  `json:"buddy_user_id"`
	BuddyName   sql.NullString `json:"buddy_name"`
	CheckedInAt sql.NullTime   `json:"checked_in_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Broadcast struct {
	BroadcastID    int64         `json:"broadcast_id"`
	Message        string        `json:"message"`
	Audience       string        `json:"audience"`
	SenderUserID   int64         `json:"sender_user_id"`
	PushEnabled    bool          `json:"push_enabled"`
	ScheduledAt    sql.NullTime  `json:"scheduled_at"`
	SentAt         sql.NullTime  `json:"sent_at"`
	Status         string        `json:"status"`
	RecipientCount sql.NullInt64 `json:"recipient_count"`
	SentCount      sql.NullInt64 `json:"sent_count"`
	FailedCount    sql.NullInt64 `json:"failed_count"`
	CreatedAt      sql.NullTime  `json:"created_at"`
	Title          string        `json:"title"`
}

type EmergencyContact struct {
	ContactID    int64          `json:"contact_id"`
	Name         string         `json:"name"`
	Number       string         `json:"number"`
	Description  sql.NullString `json:"description"`
	IsDefault    bool           `json:"is_default"`
	IsActive     bool           `json:"is_active"`
	DisplayOrder int64          `json:"display_order"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type Outbox struct {
	OutboxID    int64          `json:"outbox_id"`
	MessageType string         `json:"message_type"`
	Recipient   string         `json:"recipient"`
	Payload     sql.NullString `json:"payload"`
	Status      string         `json:"status"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	SentAt      sql.NullTime   `json:"sent_at"`
	RetryCount  sql.NullInt64  `json:"retry_count"`
	UserID      sql.NullInt64  `json:"user_id"`
	SendAt      time.Time      `json:"send_at"`
}

type PushSubscription struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
	Endpoint  string         `json:"endpoint"`
	P256dhKey string         `json:"p256dh_key"`
	AuthKey   string         `json:"auth_key"`
	UserAgent sql.NullString `json:"user_agent"`
	Platform  sql.NullString `json:"platform"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Report struct {
	ReportID     int64           `json:"report_id"`
	BookingID    sql.NullInt64   `json:"booking_id"`
	UserID       sql.NullInt64   `json:"user_id"`
	Severity     int64           `json:"severity"`
	Message      sql.NullString  `json:"message"`
	CreatedAt    sql.NullTime    `json:"created_at"`
	Latitude     sql.NullFloat64 `json:"latitude"`
	Longitude    sql.NullFloat64 `json:"longitude"`
	GpsAccuracy  sql.NullFloat64 `json:"gps_accuracy"`
	GpsTimestamp sql.NullTime    `json:"gps_timestamp"`
	ArchivedAt   sql.NullTime    `json:"archived_at"`
}

type Schedule struct {
	ScheduleID      int64          `json:"schedule_id"`
	Name            string         `json:"name"`
	CronExpr        string         `json:"cron_expr"`
	StartDate       sql.NullTime   `json:"start_date"`
	EndDate         sql.NullTime   `json:"end_date"`
	DurationMinutes int64          `json:"duration_minutes"`
	Timezone        sql.NullString `json:"timezone"`
}

type User struct {
	UserID    int64          `json:"user_id"`
	Phone     string         `json:"phone"`
	Name      sql.NullString `json:"name"`
	CreatedAt sql.NullTime   `json:"created_at"`
	Role      string         `json:"role"`
}
