// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AdminBulkDeleteSchedules(ctx context.Context, scheduleIds []int64) error
	AdminBulkDeleteUsers(ctx context.Context, userIds []int64) error
	AdminGetReportWithContext(ctx context.Context, reportID int64) (AdminGetReportWithContextRow, error)
	AdminListArchivedReportsWithContext(ctx context.Context) ([]AdminListArchivedReportsWithContextRow, error)
	AdminListReportsWithContext(ctx context.Context) ([]AdminListReportsWithContextRow, error)
	ArchiveReport(ctx context.Context, reportID int64) error
	// Award an achievement to a user
	AwardAchievement(ctx context.Context, arg AwardAchievementParams) error
	// Points System Queries
	// Award points to a user for a specific reason
	AwardPoints(ctx context.Context, arg AwardPointsParams) error
	BulkArchiveReports(ctx context.Context, reportIds []int64) error
	CountUsers(ctx context.Context) (int64, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateBroadcast(ctx context.Context, arg CreateBroadcastParams) (Broadcast, error)
	CreateEmergencyContact(ctx context.Context, arg CreateEmergencyContactParams) (EmergencyContact, error)
	CreateOffShiftReport(ctx context.Context, arg CreateOffShiftReportParams) (Report, error)
	CreateOutboxItem(ctx context.Context, arg CreateOutboxItemParams) (Outbox, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteBooking(ctx context.Context, bookingID int64) error
	DeleteBroadcast(ctx context.Context, broadcastID int64) error
	DeleteEmergencyContact(ctx context.Context, contactID int64) error
	DeleteReport(ctx context.Context, reportID int64) error
	DeleteSchedule(ctx context.Context, scheduleID int64) error
	DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error
	DeleteUser(ctx context.Context, userID int64) error
	GetAllSubscriptions(ctx context.Context) ([]GetAllSubscriptionsRow, error)
	GetAuditEventStats(ctx context.Context) (GetAuditEventStatsRow, error)
	GetAuditEventsByTypeStats(ctx context.Context) ([]GetAuditEventsByTypeStatsRow, error)
	// Get achievements a user hasn't earned yet
	GetAvailableAchievements(ctx context.Context, userID int64) ([]GetAvailableAchievementsRow, error)
	GetBookingByID(ctx context.Context, bookingID int64) (Booking, error)
	GetBookingByScheduleAndStartTime(ctx context.Context, arg GetBookingByScheduleAndStartTimeParams) (Booking, error)
	// Admin Dashboard Metrics Queries
	// Get booking-based metrics for dashboard (will be combined with slot data in Go)
	GetBookingMetrics(ctx context.Context, arg GetBookingMetricsParams) (GetBookingMetricsRow, error)
	// Get booking patterns by time slot from historical data
	GetBookingPatternsByTimeSlot(ctx context.Context) ([]GetBookingPatternsByTimeSlotRow, error)
	// Get all bookings in date range with check-in and report status
	GetBookingsInDateRange(ctx context.Context, arg GetBookingsInDateRangeParams) ([]GetBookingsInDateRangeRow, error)
	GetBroadcastByID(ctx context.Context, broadcastID int64) (Broadcast, error)
	GetDefaultEmergencyContact(ctx context.Context) (EmergencyContact, error)
	GetEmergencyContactByID(ctx context.Context, contactID int64) (EmergencyContact, error)
	GetEmergencyContacts(ctx context.Context) ([]EmergencyContact, error)
	// Get member contribution analysis for the past month
	GetMemberContributions(ctx context.Context) ([]GetMemberContributionsRow, error)
	GetPendingOutboxItems(ctx context.Context, limit int64) ([]Outbox, error)
	// Get recent point-earning activities across all users for activity feed
	GetRecentActivity(ctx context.Context, limit int64) ([]GetRecentActivityRow, error)
	// Limit to prevent processing too many at once
	GetRecentOutboxItemsByRecipient(ctx context.Context, arg GetRecentOutboxItemsByRecipientParams) ([]Outbox, error)
	GetReportByBookingID(ctx context.Context, bookingID sql.NullInt64) (Report, error)
	GetReportsForAutoArchiving(ctx context.Context) ([]GetReportsForAutoArchivingRow, error)
	GetScheduleByID(ctx context.Context, scheduleID int64) (Schedule, error)
	GetSubscriptionsByUser(ctx context.Context, userID int64) ([]GetSubscriptionsByUserRow, error)
	// Get leaderboard of top users by points
	GetTopUsers(ctx context.Context, limit int64) ([]GetTopUsersRow, error)
	// Get leaderboard of top users by shift count
	GetTopUsersByShifts(ctx context.Context, limit int64) ([]GetTopUsersByShiftsRow, error)
	// Get all achievements earned by a user
	GetUserAchievements(ctx context.Context, userID int64) ([]GetUserAchievementsRow, error)
	GetUserByID(ctx context.Context, userID int64) (GetUserByIDRow, error)
	GetUserByPhone(ctx context.Context, phone string) (GetUserByPhoneRow, error)
	// Get a user's current points and shift information
	GetUserPoints(ctx context.Context, userID int64) (GetUserPointsRow, error)
	// Get recent points history for a user
	GetUserPointsHistory(ctx context.Context, arg GetUserPointsHistoryParams) ([]GetUserPointsHistoryRow, error)
	// Get a specific user's rank by points
	GetUserRank(ctx context.Context, userID int64) (int64, error)
	// Get the number of shifts a user has completed in a specific month
	GetUserShiftCountForMonth(ctx context.Context, arg GetUserShiftCountForMonthParams) (int64, error)
	ListActiveSchedules(ctx context.Context, arg ListActiveSchedulesParams) ([]Schedule, error)
	ListAllSchedules(ctx context.Context) ([]Schedule, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error)
	ListAuditEventsByActor(ctx context.Context, arg ListAuditEventsByActorParams) ([]ListAuditEventsByActorRow, error)
	ListAuditEventsByDateRange(ctx context.Context, arg ListAuditEventsByDateRangeParams) ([]ListAuditEventsByDateRangeRow, error)
	ListAuditEventsByTarget(ctx context.Context, arg ListAuditEventsByTargetParams) ([]ListAuditEventsByTargetRow, error)
	ListAuditEventsByType(ctx context.Context, arg ListAuditEventsByTypeParams) ([]ListAuditEventsByTypeRow, error)
	ListAuditEventsWithFilters(ctx context.Context, arg ListAuditEventsWithFiltersParams) ([]ListAuditEventsWithFiltersRow, error)
	ListBookingsByUserID(ctx context.Context, userID int64) ([]Booking, error)
	ListBookingsByUserIDWithSchedule(ctx context.Context, userID int64) ([]ListBookingsByUserIDWithScheduleRow, error)
	ListBroadcasts(ctx context.Context) ([]Broadcast, error)
	ListBroadcastsWithSender(ctx context.Context) ([]ListBroadcastsWithSenderRow, error)
	ListPendingBroadcasts(ctx context.Context) ([]Broadcast, error)
	ListReportsByUserID(ctx context.Context, userID sql.NullInt64) ([]Report, error)
	ListUsers(ctx context.Context, searchTerm interface{}) ([]ListUsersRow, error)
	SetDefaultEmergencyContact(ctx context.Context, contactID int64) error
	UnarchiveReport(ctx context.Context, reportID int64) error
	UpdateBookingCheckIn(ctx context.Context, arg UpdateBookingCheckInParams) (Booking, error)
	UpdateBroadcastStatus(ctx context.Context, arg UpdateBroadcastStatusParams) (Broadcast, error)
	UpdateEmergencyContact(ctx context.Context, arg UpdateEmergencyContactParams) (EmergencyContact, error)
	UpdateOutboxItemStatus(ctx context.Context, arg UpdateOutboxItemStatusParams) (Outbox, error)
	UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	// Update user's shift count and last activity
	UpdateUserShiftCount(ctx context.Context, userID int64) error
	// Update user's total points (should be called after AwardPoints)
	UpdateUserTotalPoints(ctx context.Context, arg UpdateUserTotalPointsParams) error
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error
}

var _ Querier = (*Queries)(nil)
