// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reports.sql

package db

import (
	"context"
	"database/sql"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    booking_id,
    severity,
    message
) VALUES (
    ?,
    ?,
    ?
)
RETURNING report_id, booking_id, severity, message, created_at
`

type CreateReportParams struct {
	BookingID int64          `json:"booking_id"`
	Severity  int64          `json:"severity"`
	Message   sql.NullString `json:"message"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, createReport, arg.BookingID, arg.Severity, arg.Message)
	var i Report
	err := row.Scan(
		&i.ReportID,
		&i.BookingID,
		&i.Severity,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const getReportByBookingID = `-- name: GetReportByBookingID :one
SELECT report_id, booking_id, severity, message, created_at FROM reports
WHERE booking_id = ?
`

func (q *Queries) GetReportByBookingID(ctx context.Context, bookingID int64) (Report, error) {
	row := q.db.QueryRowContext(ctx, getReportByBookingID, bookingID)
	var i Report
	err := row.Scan(
		&i.ReportID,
		&i.BookingID,
		&i.Severity,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listReportsByUserID = `-- name: ListReportsByUserID :many
SELECT r.report_id, r.booking_id, r.severity, r.message, r.created_at 
FROM reports r
JOIN bookings b ON r.booking_id = b.booking_id
WHERE b.user_id = ?
ORDER BY r.created_at DESC
`

func (q *Queries) ListReportsByUserID(ctx context.Context, userID int64) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listReportsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ReportID,
			&i.BookingID,
			&i.Severity,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
