name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GO_VERSION: '1.24'
  NODE_VERSION: '20'

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable pnpm
        run: corepack enable pnpm

      - name: Go - Download dependencies
        run: go mod download

      - name: Go - Run tests
        env:
          DATABASE_PATH: ./test.db
          JWT_SECRET: test-secret
        run: go test -v ./...

      - name: Go - Build
        run: go build -o night-owls-server ./cmd/server

      - name: Frontend - Install dependencies
        working-directory: ./app
        run: pnpm install --frozen-lockfile

      - name: Frontend - Type check
        working-directory: ./app
        run: pnpm run check

      - name: Frontend - Build
        working-directory: ./app
        run: pnpm run build

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: night-owls-go:test 