name: Security Monitoring

on:
  schedule:
    # Run security scans daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'app/package.json'
      - 'app/pnpm-lock.yaml'

jobs:
  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Scan Docker image for vulnerabilities
        if: github.event_name == 'schedule'
        run: |
          docker pull ghcr.io/fermain/night-owls-go:latest || echo "Image not found, skipping scan"
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/Library/Caches:/root/.cache/ \
            aquasec/trivy:latest image ghcr.io/fermain/night-owls-go:latest || true

  dependency-updates:
    name: Check for Dependency Updates
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Check for Go module updates
        run: |
          echo "## Go Dependencies Status" >> $GITHUB_STEP_SUMMARY
          go list -u -m all | grep -E '\[.*\]' || echo "All Go dependencies are up to date" >> $GITHUB_STEP_SUMMARY

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable pnpm
        run: corepack enable pnpm

      - name: Check for Node.js dependency updates
        working-directory: ./app
        run: |
          echo "## Frontend Dependencies Status" >> $GITHUB_STEP_SUMMARY
          pnpm outdated || echo "Frontend dependency check completed" >> $GITHUB_STEP_SUMMARY 